(cl:defpackage robot_arm_pkg-msg
  (:use )
  (:export
   "<SORTERENACTION>"
   "SORTERENACTION"
   "<SORTERENACTIONFEEDBACK>"
   "SORTERENACTIONFEEDBACK"
   "<SORTERENACTIONGOAL>"
   "SORTERENACTIONGOAL"
   "<SORTERENACTIONRESULT>"
   "SORTERENACTIONRESULT"
   "<SORTERENFEEDBACK>"
   "SORTERENFEEDBACK"
   "<SORTERENGOAL>"
   "SORTERENGOAL"
   "<SORTERENRESULT>"
   "SORTERENRESULT"
  ))

