; Auto-generated. Do not edit!


(cl:in-package robot_arm_pkg-msg)


;//! \htmlinclude sorterenGoal.msg.html

(cl:defclass <sorterenGoal> (roslisp-msg-protocol:ros-message)
  ((doel_positie
    :reader doel_positie
    :initarg :doel_positie
    :type cl:string
    :initform ""))
)

(cl:defclass sorterenGoal (<sorterenGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <sorterenGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'sorterenGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_pkg-msg:<sorterenGoal> is deprecated: use robot_arm_pkg-msg:sorterenGoal instead.")))

(cl:ensure-generic-function 'doel_positie-val :lambda-list '(m))
(cl:defmethod doel_positie-val ((m <sorterenGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_pkg-msg:doel_positie-val is deprecated.  Use robot_arm_pkg-msg:doel_positie instead.")
  (doel_positie m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <sorterenGoal>) ostream)
  "Serializes a message object of type '<sorterenGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'doel_positie))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'doel_positie))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <sorterenGoal>) istream)
  "Deserializes a message object of type '<sorterenGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'doel_positie) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'doel_positie) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<sorterenGoal>)))
  "Returns string type for a message object of type '<sorterenGoal>"
  "robot_arm_pkg/sorterenGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'sorterenGoal)))
  "Returns string type for a message object of type 'sorterenGoal"
  "robot_arm_pkg/sorterenGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<sorterenGoal>)))
  "Returns md5sum for a message object of type '<sorterenGoal>"
  "d0e6e9e8936cc5ed9f03d68751151301")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'sorterenGoal)))
  "Returns md5sum for a message object of type 'sorterenGoal"
  "d0e6e9e8936cc5ed9f03d68751151301")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<sorterenGoal>)))
  "Returns full string definition for message of type '<sorterenGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string doel_positie~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'sorterenGoal)))
  "Returns full string definition for message of type 'sorterenGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string doel_positie~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <sorterenGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'doel_positie))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <sorterenGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'sorterenGoal
    (cl:cons ':doel_positie (doel_positie msg))
))
