; Auto-generated. Do not edit!


(cl:in-package robot_arm_pkg-msg)


;//! \htmlinclude sorterenResult.msg.html

(cl:defclass <sorterenResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass sorterenResult (<sorterenResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <sorterenResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'sorterenResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_pkg-msg:<sorterenResult> is deprecated: use robot_arm_pkg-msg:sorterenResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <sorterenResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_pkg-msg:success-val is deprecated.  Use robot_arm_pkg-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <sorterenResult>) ostream)
  "Serializes a message object of type '<sorterenResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <sorterenResult>) istream)
  "Deserializes a message object of type '<sorterenResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<sorterenResult>)))
  "Returns string type for a message object of type '<sorterenResult>"
  "robot_arm_pkg/sorterenResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'sorterenResult)))
  "Returns string type for a message object of type 'sorterenResult"
  "robot_arm_pkg/sorterenResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<sorterenResult>)))
  "Returns md5sum for a message object of type '<sorterenResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'sorterenResult)))
  "Returns md5sum for a message object of type 'sorterenResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<sorterenResult>)))
  "Returns full string definition for message of type '<sorterenResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'sorterenResult)))
  "Returns full string definition for message of type 'sorterenResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool success~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <sorterenResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <sorterenResult>))
  "Converts a ROS message object to a list"
  (cl:list 'sorterenResult
    (cl:cons ':success (success msg))
))
