; Auto-generated. Do not edit!


(cl:in-package robot_arm_pkg-msg)


;//! \htmlinclude SorterenGoal.msg.html

(cl:defclass <SorterenGoal> (roslisp-msg-protocol:ros-message)
  ((tf_frame
    :reader tf_frame
    :initarg :tf_frame
    :type cl:string
    :initform "")
   (doel_positie
    :reader doel_positie
    :initarg :doel_positie
    :type cl:string
    :initform ""))
)

(cl:defclass SorterenGoal (<SorterenGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SorterenGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SorterenGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_arm_pkg-msg:<SorterenGoal> is deprecated: use robot_arm_pkg-msg:SorterenGoal instead.")))

(cl:ensure-generic-function 'tf_frame-val :lambda-list '(m))
(cl:defmethod tf_frame-val ((m <SorterenGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_pkg-msg:tf_frame-val is deprecated.  Use robot_arm_pkg-msg:tf_frame instead.")
  (tf_frame m))

(cl:ensure-generic-function 'doel_positie-val :lambda-list '(m))
(cl:defmethod doel_positie-val ((m <SorterenGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_arm_pkg-msg:doel_positie-val is deprecated.  Use robot_arm_pkg-msg:doel_positie instead.")
  (doel_positie m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SorterenGoal>) ostream)
  "Serializes a message object of type '<SorterenGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'tf_frame))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'tf_frame))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'doel_positie))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'doel_positie))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SorterenGoal>) istream)
  "Deserializes a message object of type '<SorterenGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'tf_frame) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'tf_frame) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'doel_positie) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'doel_positie) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SorterenGoal>)))
  "Returns string type for a message object of type '<SorterenGoal>"
  "robot_arm_pkg/SorterenGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SorterenGoal)))
  "Returns string type for a message object of type 'SorterenGoal"
  "robot_arm_pkg/SorterenGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SorterenGoal>)))
  "Returns md5sum for a message object of type '<SorterenGoal>"
  "fe12904864f980fb89c80a0b6f0fc939")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SorterenGoal)))
  "Returns md5sum for a message object of type 'SorterenGoal"
  "fe12904864f980fb89c80a0b6f0fc939")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SorterenGoal>)))
  "Returns full string definition for message of type '<SorterenGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string tf_frame~%string doel_positie~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SorterenGoal)))
  "Returns full string definition for message of type 'SorterenGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%string tf_frame~%string doel_positie~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SorterenGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'tf_frame))
     4 (cl:length (cl:slot-value msg 'doel_positie))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SorterenGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SorterenGoal
    (cl:cons ':tf_frame (tf_frame msg))
    (cl:cons ':doel_positie (doel_positie msg))
))
