// Auto-generated. Do not edit!

// (in-package robot_arm_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SorterenGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.tf_frame = null;
      this.doel_positie = null;
    }
    else {
      if (initObj.hasOwnProperty('tf_frame')) {
        this.tf_frame = initObj.tf_frame
      }
      else {
        this.tf_frame = '';
      }
      if (initObj.hasOwnProperty('doel_positie')) {
        this.doel_positie = initObj.doel_positie
      }
      else {
        this.doel_positie = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SorterenGoal
    // Serialize message field [tf_frame]
    bufferOffset = _serializer.string(obj.tf_frame, buffer, bufferOffset);
    // Serialize message field [doel_positie]
    bufferOffset = _serializer.string(obj.doel_positie, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SorterenGoal
    let len;
    let data = new SorterenGoal(null);
    // Deserialize message field [tf_frame]
    data.tf_frame = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [doel_positie]
    data.doel_positie = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.tf_frame.length;
    length += object.doel_positie.length;
    return length + 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_arm_pkg/SorterenGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'fe12904864f980fb89c80a0b6f0fc939';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string tf_frame
    string doel_positie
    
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SorterenGoal(null);
    if (msg.tf_frame !== undefined) {
      resolved.tf_frame = msg.tf_frame;
    }
    else {
      resolved.tf_frame = ''
    }

    if (msg.doel_positie !== undefined) {
      resolved.doel_positie = msg.doel_positie;
    }
    else {
      resolved.doel_positie = ''
    }

    return resolved;
    }
};

module.exports = SorterenGoal;
