// Auto-generated. Do not edit!

// (in-package robot_arm_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class sorterenGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.doel_positie = null;
    }
    else {
      if (initObj.hasOwnProperty('doel_positie')) {
        this.doel_positie = initObj.doel_positie
      }
      else {
        this.doel_positie = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type sorterenGoal
    // Serialize message field [doel_positie]
    bufferOffset = _serializer.string(obj.doel_positie, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type sorterenGoal
    let len;
    let data = new sorterenGoal(null);
    // Deserialize message field [doel_positie]
    data.doel_positie = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.doel_positie.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_arm_pkg/sorterenGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'd0e6e9e8936cc5ed9f03d68751151301';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    string doel_positie
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new sorterenGoal(null);
    if (msg.doel_positie !== undefined) {
      resolved.doel_positie = msg.doel_positie;
    }
    else {
      resolved.doel_positie = ''
    }

    return resolved;
    }
};

module.exports = sorterenGoal;
